name: Change status of the assigned issue to In Progress

on:
  issues:
    types: [assigned]

jobs:
  move:
    name: Move
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Move issue to In Progress
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PROJECTS_MOVE }}
          script: |
            const issueNumber = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);

            // Fetch the projects for the repository
            const projects = await octokit.rest.projects.listForRepo({
              owner: owner,
              repo: repo
            });

            // Find the project by name
            const project = projects.data.find(proj => proj.name === "My Classic Project");

            if (!project) {
              throw new Error("Project not found");
            }

            // Get the columns for the project
            const columns = await octokit.rest.projects.listColumns({
              project_id: project.id
            });

            // Find the "In Progress" column
            const inProgressColumn = columns.data.find(column => column.name === "In Progress");

            if (!inProgressColumn) {
              throw new Error("In Progress column not found");
            }

            // Create a card for the issue in the "In Progress" column
            await octokit.rest.projects.createCard({
              column_id: inProgressColumn.id,
              content_id: issueNumber,
              content_type: 'Issue'
            });

            console.log(`Moved issue #${issueNumber} to "In Progress"`);
