name: Move Assigned Issue to In Progress

on:
  issues:
    types: [assigned]

jobs:
  move:
    name: Move
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to In Progress
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PROJECTS_MOVE }}
          script: |
            const issueNumber = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            // Get the issue details
            const issue = await github.rest.issues.get({
              owner: owner,
              repo: repo,
              issue_number: issueNumber
            });

            // Get the list of projects the issue is associated with
            const issueProjects = await github.rest.projects.listForRepo({
              owner: owner,
              repo: repo
            });

            // Find the project item for the specific project
            const project = issueProjects.data.find(project => project.name === "test1-project");

            if (project) {
              // Get the columns for the project
              const columns = await github.rest.projects.listColumns({
                project_id: project.id
              });

              // Find the "In Progress" column
              const inProgressColumn = columns.data.find(column => column.name === "In Progress");

              if (inProgressColumn) {
                // Create a project card for the issue in the "In Progress" column
                await github.rest.projects.createCard({
                  column_id: inProgressColumn.id,
                  content_id: issue.data.id,
                  content_type: 'Issue'
                });

                console.log(`Moved issue #${issueNumber} to "In Progress"`);
              } else {
                console.log(`"In Progress" column not found in project`);
              }
            } else {
              console.log(`Issue #${issueNumber} is not part of the specified project`);
            }

