name: Move Assigned Issue to In Progress

on:
  issues:
    types: [assigned]

jobs:
  move:
    name: Move
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to In Progress
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PROJECTS_MOVE }}
          script: |
            const issueNumber = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            // Get the issue details
            const issue = await github.rest.issues.get({
              owner: owner,
              repo: repo,
              issue_number: issueNumber
            });

            // Get the list of projects for the repository
            const projects = await github.rest.projects.listForRepo({
              owner: owner,
              repo: repo
            });

            // Find the specific project
            const project = projects.data.find(proj => proj.name === "test1-project");

            if (project) {
              // Get the columns for the project
              const columns = await github.rest.projects.listColumns({
                project_id: project.id
              });

              // Find the "In Progress" column
              const inProgressColumn = columns.data.find(column => column.name === "In Progress");

              if (inProgressColumn) {
                // Check if the issue is already part of the project
                const projectCards = await github.rest.projects.listCards({
                  column_id: inProgressColumn.id
                });

                const issueCard = projectCards.data.find(card => card.content_url === issue.data.url);

                if (!issueCard) {
                  // Add the issue to the first column if it's not part of the project
                  const firstColumn = columns.data[0];
                  await github.rest.projects.createCard({
                    column_id: firstColumn.id,
                    content_id: issue.data.id,
                    content_type: 'Issue'
                  });
                }

                // Move the issue to the "In Progress" column
                const issueCards = await github.rest.projects.listCards({
                  column_id: firstColumn.id
                });

                const card = issueCards.data.find(card => card.content_url === issue.data.url);

                if (card) {
                  await github.rest.projects.moveCard({
                    card_id: card.id,
                    position: 'top',
                    column_id: inProgressColumn.id
                  });

                  console.log(`Moved issue #${issueNumber} to "In Progress"`);
                } else {
                  console.log(`Could not find the card for issue #${issueNumber}`);
                }
              } else {
                console.log(`"In Progress" column not found in project`);
              }
            } else {
              console.log(`Project "Your Project Name" not found`);
            }
